### ISSUE TITLE
Loader chaining order?

### ISSUE THREAD

**Issue by irvinebroque** [gurdasnijor/component-flow-loader#3]
Hey, really enjoyed your talk on Wednesday.

Trying to get this working with an existing project with the following loader config:

      { test: /\.js$/, exclude: /node_modules/, loaders: ['react-hot', '6to5-loader', 'jsx?harmony'] }

I tried all the permutations of where `component-flow-loader` could be chained, like:

      { test: /\.js$/, exclude: /node_modules/, loaders: ['react-hot', '6to5-loader', 'component-flow', 'jsx?harmony'] }

My modules get instrumented properly, but then `component-flow-loader`'s own runtime-components don't get the JSX transform and throw the following error:

		ERROR in ./~/component-flow-loader/runtime_components/root_wrapper.js
		Module parse failed: /Users/brendan/code/buildingos/node_modules/component-flow-loader/runtime_components/root_wrapper.js Line 67: Unexpected token <
		You may need an appropriate loader to handle this file type.
		| 
		|     return (
		|       <div>
		|         <div className={this.state.is3DView ? "cfl_viewport" : null}>
		|           <div className="cfl_rotate-wrapper" style={this.state.is3DView ? transformString: null}>
		 @ ./client.js 1:23-90

		ERROR in ./~/component-flow-loader/runtime_components/component_wrapper.js
		Module parse failed: /Users/brendan/code/buildingos/node_modules/component-flow-loader/runtime_components/component_wrapper.js Line 124: Unexpected token <
		You may need an appropriate loader to handle this file type.
		| 
		|     return (
		|       <div className={wrapperClass} style={{
		|         "transform": "translateZ(" + this._mountDepth * 3 + "px)",
		|         "height": this.state.height,
		 @ ./views/App.js 1:28-100

Anything I'm missing here?

**Comment by gurdasnijor** [comment]
Thanks for testing this out: pushed a commit that'll make this module transform its own jsx.

**Comment by irvinebroque** [comment]
@gurdasnijor - thank you!
